# Importación de Librerías y Carga del Modelo spaCy

In [6]:
import sys
import os
import warnings
import spacy
import pandas as pd
from pathlib import Path
warnings.filterwarnings('ignore')
sys.path.append(os.path.abspath(".."))
from src.data.mongo_storage import _get_default_collection
from src.data.preprocessor import token_spacy
from src.pos_tagging.Taggin_spacy import apply_pos_tagging_spacy

print('✓ Librerías importadas correctamente')

✓ Librerías importadas correctamente

# Carga del Dataset

In [7]:
# Cargar canciones desde MongoDB
col = _get_default_collection()
docs = list(col.find({}, {
    '_id': 1, 'Song': 1, 'Artist': 1, 'Genre': 1,
    'Song year': 1, 'Lyrics': 1, 'Language': 1
}))

df = pd.DataFrame(docs)
print(f'✓ {len(df)} canciones cargadas desde MongoDB')
df.head()

✓ 9246 canciones cargadas desde MongoDB

,_id,Song,Artist,Genre,Language,Lyrics,Song year
0,69d7e6fb0126095ee5e13af6,craftsmanship,buck-65,Hip-Hop,en,Most folks spend their days daydreaming of fin...,2005
1,69d7e6fb0126095ee5e13af7,come-on-out,the-elwins,Indie,en,Take your cold hands and put them on my face S...,2012
2,69d7e6fb0126095ee5e13af8,riot,bullet-for-my-valentine,Metal,en,Are you ready its time for war Well break down...,2013
3,69d7e6fb0126095ee5e13af9,that-s-what-girls-do,dream-street,Pop,en,You ask me why I change the color of my hair Y...,2007
4,69d7e6fb0126095ee5e13afa,believe-in-a-dollar,cassidy,Hip-Hop,en,Do you believe in magic in a young girls heart...,2012

# Tokenización

In [8]:
df = token_spacy(df)
print('✓ Tokenización con spaCy completada')
df.head()

✓ Tokenización con spaCy completada

,_id,Song,Artist,Genre,Language,Lyrics,Song year,tokens
0,69d7e6fb0126095ee5e13af6,craftsmanship,buck-65,Hip-Hop,en,Most folks spend their days daydreaming of fin...,2005,"[Most, folks, spend, their, days, daydreaming,..."
1,69d7e6fb0126095ee5e13af7,come-on-out,the-elwins,Indie,en,Take your cold hands and put them on my face S...,2012,"[Take, your, cold, hands, and, put, them, on, ..."
2,69d7e6fb0126095ee5e13af8,riot,bullet-for-my-valentine,Metal,en,Are you ready its time for war Well break down...,2013,"[Are, you, ready, its, time, for, war, Well, b..."
3,69d7e6fb0126095ee5e13af9,that-s-what-girls-do,dream-street,Pop,en,You ask me why I change the color of my hair Y...,2007,"[You, ask, me, why, I, change, the, color, of,..."
4,69d7e6fb0126095ee5e13afa,believe-in-a-dollar,cassidy,Hip-Hop,en,Do you believe in magic in a young girls heart...,2012,"[Do, you, believe, in, magic, in, a, young, gi..."

# POS Taggin

In [9]:
df = apply_pos_tagging_spacy(df)
print('✓ POS tagging con spaCy completado y guardado en MongoDB')
df.head()

pos_tags.spacy guardados en MongoDB: 9246/9246 canciones
✓ POS tagging con spaCy completado y guardado en MongoDB

,_id,Song,Artist,Genre,Language,Lyrics,Song year,tokens,pos_tags_spacy
0,69d7e6fb0126095ee5e13af6,craftsmanship,buck-65,Hip-Hop,en,Most folks spend their days daydreaming of fin...,2005,"[Most, folks, spend, their, days, daydreaming,...","[{'token': 'Most', 'pos': 'ADJ', 'tag': 'JJS',..."
1,69d7e6fb0126095ee5e13af7,come-on-out,the-elwins,Indie,en,Take your cold hands and put them on my face S...,2012,"[Take, your, cold, hands, and, put, them, on, ...","[{'token': 'Take', 'pos': 'VERB', 'tag': 'VB',..."
2,69d7e6fb0126095ee5e13af8,riot,bullet-for-my-valentine,Metal,en,Are you ready its time for war Well break down...,2013,"[Are, you, ready, its, time, for, war, Well, b...","[{'token': 'Are', 'pos': 'AUX', 'tag': 'VBP', ..."
3,69d7e6fb0126095ee5e13af9,that-s-what-girls-do,dream-street,Pop,en,You ask me why I change the color of my hair Y...,2007,"[You, ask, me, why, I, change, the, color, of,...","[{'token': 'You', 'pos': 'PRON', 'tag': 'PRP',..."
4,69d7e6fb0126095ee5e13afa,believe-in-a-dollar,cassidy,Hip-Hop,en,Do you believe in magic in a young girls heart...,2012,"[Do, you, believe, in, magic, in, a, young, gi...","[{'token': 'Do', 'pos': 'AUX', 'tag': 'VBP', '..."

In [10]:
# Verificar que se guardaron correctamente en MongoDB
ejemplo = col.find_one({'pos_tags.spacy': {'$ne': None}})
if ejemplo:
    print(f"Canción: {ejemplo.get('Song')}")
    print(f"POS tags spaCy (primeros 5): {ejemplo['pos_tags']['spacy'][:5]}")
else:
    print('No se encontraron documentos con pos_tags.spacy')

Canción: craftsmanship
POS tags spaCy (primeros 5): [{'token': 'Most', 'pos': 'ADJ', 'tag': 'JJS', 'lemma': 'Most'}, {'token': 'folks', 'pos': 'NOUN', 'tag': 'NNS', 'lemma': 'folk'}, {'token': 'spend', 'pos': 'VERB', 'tag': 'VBP', 'lemma': 'spend'}, {'token': 'their', 'pos': 'PRON', 'tag': 'PRP$', 'lemma': 'their'}, {'token': 'days', 'pos': 'NOUN', 'tag': 'NNS', 'lemma': 'day'}]